# Generated by Django 4.2.5 on 2023-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
