# Generated by Django 4.2.5 on 2023-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0002_alter_adminuser_email_alter_adminuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
