# Generated by Django 4.2.5 on 2023-09-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0003_alter_adminuser_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_1", models.CharField(max_length=255)),
                ("team_2", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=255)),
            ],
        ),
    ]
